module.exports.config = {
    name: "chuilientuc",
    version: "1.0.0",
    hasPermssion: 1,
    credits: "...",
    description: "Tag liên tục người bạn tag trong 5 lần\nCó thể gọi là gọi hồn người đó",
    commandCategory: "group",
    usages: "chuilientuc @mention",
    cooldowns: 10,
    dependencies: {
        "fs-extra": "",
        "axios": ""
    }
}

module.exports.run = async function({ api, args, Users, event}) {
    var mention = Object.keys(event.mentions)[0];
    if(!mention) return api.sendMessage("Cần phải tag 1 người bạn muốn chửi", event.threadID);
 let name =  event.mentions[mention];
    var arraytag = [];
        arraytag.push({id: mention, tag: name});
    var a = function (a) { api.sendMessage(a, event.threadID); }
a("Ok. Do You Know? !");
setTimeout(() => {a({body: "Đ!t con mẹ mày" + " " + name, mentions: arraytag})}, 3000);
setTimeout(() => {a({body: "Mày ra đây tao bảo" + " " + name, mentions: arraytag})}, 5000);
setTimeout(() => {a({body: "Hiện hồn nhanh con chó" + " " + name, mentions: arraytag})}, 7000);
setTimeout(() => {a({body: "DKM!!!, Đớp lời bọn tao như 1 con chó!!! ,Ám chỉ thế mà vẫn địt hiểu à? ,Tao đéo cần phải bắt chuyện!!!, Phò có khác!!!, Con đéo nào cũng như con nào!!! ,Hài!!!" + " " + name, mentions: arraytag})}, 9000);
setTimeout(() => {a({body: "Loại chó đẻ nứng lồn mong manh dễ vỡ , :)) tao địt nát lồn khí tụ quanh lồn phong ba tinh trùng vào bảng mặt lồn nhà mày :)) , loại con phò rẻ tiền non nớt bại não , loại ngu ngục hãm cặc , con đĩ chó vô danh mà cứ tưởng là nhà thơ tài ba hả thằng mặt lồn 😔 tao lôi cả dòng họ nội ngoại cô gì chú bát tao đụ nát lồn bể trứng , nát cặc rách lồn :b cả nhà mày ra , loại động vật 4 chân biết sủa nhưng đéo biết cắn , trai tân mà tưởng mình là tổng thống à🥰 , thôi hãy về nới thuộc về mày đi nói đạo lí thì vô rừng mà chơi với khỉ với ếch đi con nha:) nới này không giành cho mày rồi con à đi war không ngôn mãi bại con nhé , thương lắm mới nói nè , :)) đéo biết war về bú lồn mẹ mà học hỏi thêm đi rồi hãy đi tap thì đéo lại ngôn thì được vài câu mà toàn trên mạng:) có mấy câu cụ mày còn bt trên top top 😔 chửi văn minh hả :)) vậy thôi đừng kê con nha hãm vãi đạo lí trên mạng thì nín bú cặc cha mày mà ăn năn xám hối mãi ghét thằng mặt lồn nhà mày🥰!" + " " + name, mentions: arraytag})}, 12000);
setTimeout(() => {a({body: "mặt lồn chó quàu mèo gặm trình war như con dòi ngặm xác chết tưởng đâu là hay không ngờ lại gặp chị mày đây chuyên trị mấy con phò lồn âm binh ngu dốt để tạo đì mày xuống 18 tầng địa ngục cho mày làm cô hồn tình dục cho mấy con cô hồn dạ quỷ khác để gái mẹ và thằng cha già mồm đầy cứt trâu của mày phải lặn lội khắp nơi cạo đầu sám hối đi tu để chị mày tha thứ và cho 2 mặt lồn rách nát là cha và gái mẹ mày xuống cứu nhưng không ngờ đi được nữa đường thì gái mẹ mày đã bị bọn âm binh hiếp dâm xé xác vức lồn ra bãi tha ma còn thằng cha mày phải chịu cảnh số phận mất vợ mất con mà sinh bệnh tử vong để cô hồn dạ quỷ vất vưởng như mày phải trả giá về những hành động ngu lồn như giờ thì phải bị tao đì ở dưới đó 3 đời 7 kiếp nha" + " " + name, mentions: arraytag})}, 15000);
setTimeout(() => {a({body: "đĩ mẹ dám gáy mà đi phốt não chứa tinh trùng ba m àk? đm nứng thì ra đường Trần Duy Hưng còn mun chs thì tao chs cùng m nè có cần tao đập m tuột lông lồn hông vậy có học thức hk vậy rảnh xuống 18 tầng địa ngục chết mẹ cho rùi đi chó mà đòi lên giọng với tao ák lm người hk mun mun Im idol fb? tháng cô hồn qua rùi đừng Im cô hồn bớt tạo nghiệp tu lại hộ 3 còn m thik gì thì gặp tao? dm đell mun war thì đừng chạm tao cho mất công sống cho đời sau con cháu nó nể sống chó ngta khinh bỉ thôi đ!t mẹ giữ hơi mà thở bớt sủa group tao thứ cha sinh mẹ đẻ đell dc dạy dỗ hẳn hoi thì để ây tao dạy con ôn âm binh m nhá để tạo kiu diêm vương quỷ sai lôi lồn m xuống 18 tầng địa ngục cho hết nổi ổ uế m gây ra mẹ m đẻ m ra đau lồn đẻ đc đứa con nửng mu như m mặt lồn cứ tưởng mặt vàng để tao vả cho bay dập lồn sồn sồn nhảy cẫng lên sủa để tạo đạp m xuống địa ngục Im đầu trâu mặt ngựa cho m hết nứng lồn dùng ngôn cùng m để dí tao ây nè con mặt lồn tai ương đell dc dạy dỗ hẳn hoi giờ m có ngoi lồn lên sủa t thì t cũng đạp m xuống cho những thứ tai ương ở địa ngục địt nát cái lồn thủi của m tai ương nghiệp chủng súc vật tưởng hay lắm ai dè cũng chỉ là chó đớp cức để tạo cho cu giả m đ!t cho bớt nửng nha dập cht cái lồn thúi m chui lên từ thùng rác mà tưởng ngoi lên từ thiên đường hạ lồn thái đell ai đ!t tạo xẻo lồn m cho chó nhà tao ăn m tin hông? đm bại trận 1 lần h ngoi lên tạp nx hả cắn dell dc đi phốt box tạo nhằm cc quá bây Đụ mẹ tụi mầy bị ngáo lồn àk ăn ở hk hog có chx j lm hả mấy đứa đỉ lồn dòng cái thứ chó đẻ j đâu dị nãy h t nhịn hơi bị đủ r nhe đụ mẹ tụi m muốn đụ ik ra chỗ khác mà đụ nghe mấy đứa lồn thứ âm binh j đâu ă có sủa thì cx sủa" + " " + name, mentions: arraytag})}, 17000);
setTimeout(() => {a({body: "bốc xác con cẩu tặc mẫn nhi lên 18 tầng mây xong một tay tao phủi con thú hồng liên rác rưởi như mày xuống hạ giới rồi kêu diêm vương ra đì đoạ mày xuống 7 tầng địa ngục nhấn đầu mày xuống sông hoàng hà để cứt trong đầu mày được rửa sạch nha quá khập khiễng khi mà phải để tao khạc ngôn như khạc đờm để type với con chó chân ướt chân ráo mà bày đặt làm bố thiên hạ nhảy lên đầu tao ngồi chê mẹ mày ngôn rách ngôn nát là sao hả con xàm cứt, câm cụ m cái họng lồn xàm xí đú cứ ngồi gia giảng đạo đức cho mấy con óc cứt não tôm rình mò cắn lồn cạp bướm chị đi, trình thì thở được dăm ba câu như con thú nhồi bông lông nhông loắt choắt, đụ đỉ mẹ đúng là âm cực dương hồi dòng đời xoay chuyển dòng họ 9981 đời nhà m nhìn cái bài vị tao lù lù trên cửa Phật có há hốc mồm cầu xin mẹ m dung thứ cho cái hạng ăn cháo lá đa như mày" + " " + name, mentions: arraytag})}, 20000);
setTimeout(() => {a({body: "Tao ném trứng thối đổ dầu đổ xăng vào nhà mày giờ" + " " + name, mentions: arraytag})}, 23000);
setTimeout(() => {a({body: "Con cặc địt mẹ mày" + " " + name, mentions: arraytag})}, 25000);
setTimeout(() => {a({body: "con tam tai nghiệt súc ru rú trong xó ẳng lên được vài ba câu ngôn rách thì tự vỗ ngực xưng tên sao?mẹ tin rằng lúc mày mới thò cái mặt dái chó thâm sì ra khỏi cái lồn của con gái mẹ xấu số thì bác sĩ đã phải khóc thương cho số phận nghiệt ngã đẻ ra con quái thai lai người ngu si đần độn tứ chi kẹp mép lồn.Đánh trống gõ mõ múa may quay cuồng như một con hề trước mặt mẹ làm mẹ cảm thấy ói mửa tởm lợm quá đi,phun ba cái ngôn rách thì đòi dập được ai? thôi thì mẹ rộng lòng cho con được hưởng diễm phúc nằm chèm bẹp dưới gót chân ngàn vàng và của mẹ Giỏi văn có ngôn thì lên thỉnh mẹ mày nè con đĩ lồn? Mày nhắm ăn được mẹ thì hãy lên đây bùng war nha con lồn bại não, ngồi ở ba hoa xàm lồn muốn dập mẹ thì mày nhả cái ngôn rác của mày ra đây húp mẹ nè đĩ? Ba hoa xàm lồn lúc mẹ dí lòi lồn thì đừng block kẻo mẹ dí cặc vào mồm mày cho mày rên ư ử như con nứng lồn đó đĩ, cứ vác mấy câu ngôn phèn cặc của mày lên đây để mẹ sục nát lồn mày hay gì vậy? Cần mẹ cầm đầu mày đút lại vào lỗ lồn mẹ mày cho bớt làm khổ nhân loại dính dáng tới con sống trong tầng lớp thiểu năng vô tri vô giác đụng mek nghĩ mình ngầu? Có to thì nhả cái ngôn của mày ra type 1-1 với mẹ ngồi đó nhảm nãy giờ thấy mệt 0 vậy đĩ? Nhân cách như nép lồn mà đòi dạy đời tao đéo = 1/3 nhân cách của tao thì mày nín cái họng mày lại 0 mẹ xiên cặc vào mồm mày từ đầu đến chân cho não mày hoạt động lại bớt úng nước lồn nha đĩ, đéo nhả ngôn của mày cho mẹ dập thì bớt ngông cái mồm lồn của mày vào đây kẻo mẹ dí mày xuống âm tiên tiễn mày đi gặp diêm vương thỉnh cái tội lỗi hồ đồ của mà,Giỏi văn có ngôn thì lên thỉnh mẹ mày nè con đĩ lồn? Mày nhắm ăn được mẹ thì hãy lên đây bùng war nha con lồn bại não, ngồi ở ba hoa xàm lồn muốn dập mẹ thì mày nhả cái ngôn rác của mày ra đây húp mẹ nè đĩ? Ba hoa xàm lồn lúc mẹ dí lòi lồn thì đừng block kẻo mẹ dí cặc vào mồm mày cho mày rên ư ử như con nứng lồn đó đĩ, cứ vác mấy câu ngôn phèn cặc của mày lên đây để mẹ sục nát lồn mày hay gì vậy? Cần mẹ cầm đầu mày đút lại vào lỗ lồn mẹ mày cho bớt làm khổ nhân loại dính dáng tới con sống" + " " + name, mentions: arraytag})}, 28500);
setTimeout(() => {a({body: "Bố mày bắn rap chết cụ mày giờ" + " " + name, mentions: arraytag})}, 31000);
setTimeout(() => {a({body: "con lồn cẩu tặc tiểu yêu tinh nhà mày 10 năm nhai được 1 câu hay sao mà spam 3 câu dài dài mà cùn như dái chó mẹ mày không để tâm thì tự ngậm mõm mà suy nghĩ chứ mắc gì dổng ra đây spam định bú dái cha hay bú lồn mẹ hay định la liếm đít tao mà ăn nói hàm hồ đợi chị mày dí mày tàn xác khỏi lên mạng ba hoa xàm lồn nhai ngôn như nhai cứt chó rồi ngồi trong góc khóc huhu hay sao mà ngu lồn tàn tạ để chị mày phải tặng mày cái lồn bát giới để trấn tĩnh âm hồn khỏi lên đây hóa ma dọa quỷ háo hức như hồng hài nhi chui ra từ bụng trư bát giới ngồi đó ngấm ngía 3 câu đại trà bình dân đến cả đứa c1 còn nhai được còn ăn được thằng đỉ mặt lồn nhà mày chừng nào tan thành xác pháo thì thôi chứ dù mày có tu tâm dưỡng tính tu tiên thành phật thì cũng chỉ là cộng rau muống nằm dưới chân chị mày mà liếm đợi chị thương xót vớt con lên về nhà đoàng tụ với gia đình khỏi boàng hoàng đợi mẹ đổi ý rồi tới lượt thằng cha mày bú đít, cho dù có thân phận thấp hèn thì cũng phải biết thân biết phận đừng có bật dậy để mẹ mày đạp xuống đáy đòi lấy oán báo ơn thì mẹ xin con chó nhà mày ngậm mõm lại chứ phun câu nào là bẩn mồm câu đấy toạc tuệ hết trúng người ta" + " " + name, mentions: arraytag})}, 36000);
setTimeout(() => {a({body: "Vậy thì xin mời nghe tao rap địt chết cả lò mày nhà con" + " " + name, mentions: arraytag})}, 39000);
setTimeout(() => {a({body: "Địt mẹ con chó" + " " + name, mentions: arraytag})}, 40000);
setTimeout(() => {a({body: "súc vật" + " " + name, mentions: arraytag})}, 65000);
setTimeout(() => {a({body: "Đầu tiên tao xin phép địt từ trên xuống dưới con" + " " + name, mentions: arraytag})}, 70000);
setTimeout(() => {a({body: "Tao địt từ lỗ lồn đến lỗ nhị con lồn" + " " + name, mentions: arraytag})}, 75000);
setTimeout(() => {a({body: "Lồn thì to như lồn trâu thủ dâm ống cống ấy nhé con" + " " + name, mentions: arraytag})}, 80000);
setTimeout(() => {a({body: "Tao địt chắc 2 thằng như tao chưa đủ lấp cái lỗ lồn nhà mày đâu" + " " + name, mentions: arraytag})}, 85000);
setTimeout(() => {a("Tao mệt rồi đéo chửi nữa")} , 90000);
setTimeout(() => {a({body: "Nào ông chủ update lyric thì chửi tiếp nhé" + " " + name, mentions: arraytag})}, 95000);
setTimeout(() => {a({body: "Cảm ơn bạn đã nghe mình chửi nha" + " " + name, mentions: arraytag})}, 100000);
setTimeout(() => {a({body: "Xin chào và hẹn gặp lại bạn ở chương trình lần sau nha" + " " + name, mentions: arraytag})}, 105000);
setTimeout(() => {a("Chào tạm biệt 🥺")} , 110000);


  
  }